### ISSUE TITLE
Shows 8 bit panel for LG G7

### ISSUE THREAD

**Issue by aerowild** [jursonovicst/gradient#2]
Thanks for the great work.
LG G7 display is officially HDR10 and is said to be a 10 bit display. But the test image shows only 256 bars for 10 bit colors on LG G7 display. The model I am using is LG G7 LM-G710N. Can it really be a only 8 bit panel?

**Comment by jursonovicst** [comment]
Hi Aerowild,

I checked this phone's specification on [www.phonemore.com](https://www.phonemore.com/lg-g7-thinq-g710n/specs/4012) and on [www.handsetdetection.com](https://www.handsetdetection.com/device-detection-database/devices/lg/lm-g710n/), and the display should support 16M colors (256*256*265=16777216), so it must be an 8 bit display according to the spec. Unfortunately, I could not found this model on lg.com.

Have you tried the test video as well? Keep in mind, that the test image is a **16 bit** PNG, the test video is a **10 bit** mp4, and I saw some Samsung TV sets, which had 10 bit display panel, they showed the video in 10 bit, but they rendered all png images in 8 bit. The manufacturer was too lazy to build the photo rendering application with 10 bit support.

You should also look very-very closely, the 10 bit gradient's bars are only 3 pixel (0.14mm) wide on this phone. I might create a gradient with fewer steps (for example, from 50% gray to 75% gray) to let test small phone displays as well.

Tamás

**Comment by aerowild** [comment]
I am sure its a 10 bit panel as many review as well as their official website says it. Some even claims that its a 12 bit panel.
 
People have discussed that here in detail
https://forum.xda-developers.com/lg-g7-thinq/help/netflix-hdr-dolby-vision-t3815617/page2

However, I have strong feeling that LG default photo viewer application can not display 10 bit. I even tried Google photos but same result.

To look for gradients, I have taking markings on bottom as reference. It matches perfectly with 8 bit bars for bothvthe cases.

I checked the video too but can not differentiate as I am unable to zoom in.

**Comment by jursonovicst** [comment]
Can you check these test sequences?

[for mobile screens](https://github.com/jursonovicst/gradient/tree/develop/mobile_test_sequences)

I split the whole gradient into 10 parts in 10 different files, now an 8bit gradient bar should be 6mm wide on a 6in display, a 10 bit bar little bigger than 1mm.

Hope this helps, tell my your results...

**Comment by jursonovicst** [comment]
Hi @aerowild,


Any luck with the new test sequences in my previous comment? Can you now confirm the 10bit support for video playback?

**Comment by aerowild** [comment]
Hi @jursonovicst,

Thanks for the updated files.

I tried the new files and here are the results.

1) It is very difficult to see any difference below gradient 20-30 file.
2) Above that, png pics still shows the only 8-bit bars for RGB and grey.
3) However, playing H265 mp4 in LG official video player, I see bars for only 8-bit. Its really difficult to notice bars for 10-bit RGB or grey color lanes.

So, looks like phone's photo viewer does not differentiate between 8 bit amd 10 bit.
